networks:
  corp:
    driver: bridge

services:
  api:
    container_name: api
    build:
      context: ./
      cache_from:
        - my-base-image:nx-base
      dockerfile: ./apps/api/Dockerfile
    image: api:nx-dev
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    networks:
      - corp
    restart: on-failure
  
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nest-next-nx-db
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  front:
    container_name: front
    build:
      context: ./
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/front/Dockerfile
    image: front:nx-dev
    ports:
      - 4000:80
    environment:
      PORT: 4000
    networks:
      - corp
    restart: on-failure

volumes:
  mysql-data: